- docs/DeveloperGuide.md
Updated for addClient and listMeeting
> Add use cases and amend description to fit MyInsuRec

- docs/DeveloperGuide.md
> DG: Add v1.2 user stories

- docs/UserGuide.md
> UG: Add Get Started section

- docs/team/thing1thing2.md
> Add PPP thing1thing2.md

- docs/UserGuide.md
> UG: add delClient command

- docs/DeveloperGuide.md
> Update use case with proper underline and hyperlinks

- docs/UserGuide.md
> UG: Update addMeeting to use INDEX

- src/main/java/seedu/address/logic/commands/AddClientCommand.java
- src/main/java/seedu/address/logic/parser/AddClientCommandParser.java
- src/main/java/seedu/address/logic/parser/ClientBookParser.java
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/AddClientCommandIntegrationTest.java
- src/test/java/seedu/address/logic/commands/AddClientCommandTest.java
- src/test/java/seedu/address/logic/parser/AddClientCommandParserTest.java
- src/test/java/seedu/address/logic/parser/ClientBookParserTest.java
- src/test/java/seedu/address/testutil/ClientUtil.java
Only refactoring has been done, parameters as expected by the command have yet to be specified ([see UG](https://ay2223s1-cs2103t-w16-4.github.io/tp/UserGuide.html#adding-a-client-addclient)), hence #5 cannot be closed yet.
> Refactor addClient command classes

- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/commands/AddClientCommand.java
- src/main/java/seedu/address/logic/commands/CommandResult.java
- src/main/java/seedu/address/logic/commands/DeleteClientCommand.java
- src/main/java/seedu/address/logic/commands/ListCommand.java
- src/main/java/seedu/address/logic/commands/ListMeetingCommand.java
- src/main/java/seedu/address/logic/parser/MyInsuRecParser.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/model/MyInsuRec.java
- src/main/java/seedu/address/model/ReadOnlyMyInsuRec.java
- src/main/java/seedu/address/model/client/Client.java
- src/main/java/seedu/address/storage/JsonSerializableMyInsuRec.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/java/seedu/address/ui/MeetingCard.java
- src/main/java/seedu/address/ui/MeetingListPanel.java
- src/main/resources/view/MeetingListCard.fxml
- src/main/resources/view/MeetingListPanel.fxml
- src/test/java/seedu/address/logic/commands/AddClientCommandTest.java
- src/test/java/seedu/address/logic/commands/ListMeetingCommandTest.java
- src/test/java/seedu/address/model/MyInsuRecTest.java
Significant changes, @AY2223S1-CS2103T-W16-4/developers all please look through this PR!
> Add listMeeting command

- src/main/java/seedu/address/logic/Logic.java
- src/main/java/seedu/address/logic/LogicManager.java
- src/main/java/seedu/address/logic/commands/CommandResult.java
- src/main/java/seedu/address/logic/commands/ViewClientCommand.java
- src/main/java/seedu/address/model/Model.java
- src/main/java/seedu/address/model/ModelManager.java
- src/main/java/seedu/address/ui/ClientDetailedView.java
- src/main/java/seedu/address/ui/ClientDetailedViewPanel.java
- src/main/java/seedu/address/ui/MainWindow.java
- src/main/resources/view/ClientDetailedView.fxml
- src/main/resources/view/ClientDetailedViewPanel.fxml
- src/test/java/seedu/address/logic/LogicManagerTest.java
- src/test/java/seedu/address/logic/commands/AddClientCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandResultTest.java
- src/test/java/seedu/address/model/ModelManagerTest.java
Added tests for related methods as well.
> Add UI for viewClient

- src/main/java/seedu/address/ui/ClientListPanel.java
- src/main/java/seedu/address/ui/MeetingListPanel.java
Instead of '1 records' we should use '1 record'.
> Fix plurality of records

- docs/DeveloperGuide.md
- docs/UserGuide.md
Includes some basic skeleton changes to help structure and organize UG.
> Update UG sikai00

- src/main/java/seedu/address/ui/ClientCard.java
If email field is empty then this bug occurs, bc there is no checks for email's optional
> Fixed UI bug

- src/main/java/seedu/address/ui/ClientDetailedView.java
same issue as https://github.com/AY2223S1-CS2103T-W16-4/tp/pull/204
> Fix UI for detailed client

- src/main/java/seedu/address/model/MyInsuRec.java
- src/main/java/seedu/address/model/client/Client.java
> Fix delClient not deleting meeting from model

- docs/UserGuide.md
Also made some minor additions to features to better describe the section.
> Update UG features: listMeeting, delProduct, listProduct

- docs/UserGuide.md
> UG: fix editClient grammar issue

- docs/UserGuide.md
> Fix all UG issues as per PE-D

- docs/DeveloperGuide.md
- src/main/java/seedu/address/storage/JsonAdaptedClient.java
- src/test/java/seedu/address/logic/commands/AddProductCommandTest.java
- src/test/java/seedu/address/logic/commands/CommandResultTest.java
- src/test/java/seedu/address/logic/commands/CommandTestUtil.java
- src/test/java/seedu/address/logic/commands/DeleteProductCommandTest.java
- src/test/java/seedu/address/logic/commands/EditClientCommandTest.java
- src/test/java/seedu/address/logic/commands/ListMeetingCommandTest.java
- src/test/java/seedu/address/testutil/ClientBuilder.java
- src/test/java/seedu/address/testutil/EditClientDescriptorBuilder.java
> Improve test code

- docs/UserGuide.md
closing #222 
Modified UG to explain how invalid parameters are handled.
> Add to command format notes

- src/main/java/seedu/address/logic/commands/EditClientCommand.java
- src/main/java/seedu/address/logic/parser/EditClientCommandParser.java
- src/test/java/seedu/address/logic/commands/EditClientCommandTest.java
- src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
Reverts AY2223S1-CS2103T-W16-4/tp#318
> Revert "Standardize EditClientCommand error msgs"

- src/main/java/seedu/address/commons/core/Messages.java
- src/main/java/seedu/address/logic/commands/AddMeetingCommand.java
- src/main/java/seedu/address/logic/commands/EditMeetingCommand.java
- src/main/java/seedu/address/logic/parser/EditMeetingCommandParser.java
- src/main/java/seedu/address/model/meeting/Description.java
Reverts AY2223S1-CS2103T-W16-4/tp#334
> Revert "Update EditMeeting error handling messages"
